name: Spell Check

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5

      - name: Spell Check Repo
        uses: crate-ci/typos@v1